name: Build and deploy blog
permissions:
  contents: write
on:
  push:
    branches:
      - master
jobs:
  build_blog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
